name: Deploy GitHub Pages

on:
  push:
    branches:
      - main
  workflow_dispatch:

# GITHUB_TOKEN에 필요한 권한 부여
permissions:
  contents: read
  pages: write
  id-token: write

# 배포 진행 중에 새로운 배포가 트리거되면 이전 배포 중단
concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    env:
      FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Pages
        uses: actions/configure-pages@v4
        with:
          enablement: true

      - name: Upload Artifacts
        uses: actions/upload-pages-artifact@v3
        with:
          # 배포할 정적 웹사이트 경로 설정
          path: './module5_SR_comparison'

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
